spring.profiles.active: local

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
  data:
    web:
      pageable:
        max-page-size: 20
        one-indexed-parameters: true
  jpa:
    open-in-view: false

dataset:
  batch-size: 500

evaluation:
  job:
    schedule-delay-ms: 3000
    limit: 10
    batch-size: 500
  model-api:
    base-url: https://evaluation.free.beeceptor.com
    path: /api/evaluation/model
    connect-timeout: 3s
    read-timeout: 30s

springdoc:
  packages-to-scan: com.dev.assignment.api
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui

---
spring.config.activate.on-profile: local

spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_log: true
        format_sql: true
    show-sql: true

  sql:
    init:
      mode: always

---
spring.config.activate.on-profile: local-test

spring:
  datasource:
    url: jdbc:h2:mem:local-db;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_log: true
        format_sql: true
    show-sql: true

  sql.init.mode: never
